"""Modbus register and entity definitions for Marstek Venus v3 hardware.

# ============================================================================
# V3 BATTERY DEFINITIONS
# WARNING: v3 registers are UNTESTED
# These definitions are for v3 battery hardware with different Modbus registers
# ============================================================================
"""

SENSOR_DEFINITIONS_V3 = [
    {
        "register": 37005,
        "scale": 1,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "name": "Battery SOC",
        "key": "battery_soc",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32105,
        "scale": 0.001,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
        "name": "Battery Total Energy",
        "key": "battery_total_energy",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 3,
        "scan_interval": "low",
    },
    {
        "register": 30100,
        "scale": 0.01,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "name": "Battery Voltage",
        "key": "battery_voltage",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 30001,
        "count": 1,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "Battery Power",
        "key": "battery_power",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 1,
        "scan_interval": "high",
    },
    {
        "name": "AC Offgrid Power",
        "register": 32302,
        "count": 1,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "key": "ac_offgrid_power",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 0,
        "scan_interval": "high",
    },
    {
        "register": 35000,
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "name": "Internal Temperature",
        "key": "internal_temperature",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 2,
        "scan_interval": "medium",
    },
    {
        "register": 30006,
        "count": 1,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "name": "AC Power",
        "key": "ac_power",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 0,
        "scan_interval": "high",
    },
    {
        "register": 33000,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "name": "Total Charging Energy",
        "key": "total_charging_energy",
        "enabled_by_default": True,
        "data_type": "uint32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33002,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "name": "Total Discharging Energy",
        "key": "total_discharging_energy",
        "enabled_by_default": True,
        "data_type": "int32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33004,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "name": "Total Daily Charging Energy",
        "key": "total_daily_charging_energy",
        "enabled_by_default": True,
        "data_type": "uint32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33006,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "name": "Total Daily Discharging Energy",
        "key": "total_daily_discharging_energy",
        "enabled_by_default": True,
        "data_type": "int32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 35100,
        "scale": 1,
        "unit": None,
        "icon": "mdi:state-machine",
        "name": "Inverter State",
        "key": "inverter_state",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "states": {
            0: "Sleep",
            1: "Standby",
            2: "Charge",
            3: "Discharge",
            4: "Backup Mode",
            5: "OTA Upgrade",
            6: "Bypass",
        },
        "scan_interval": "high",
    },
    {
        "name": "Max Cell Voltage",
        "register": 37007,
        "scale": 0.001,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "max_cell_voltage",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 3,
        "scan_interval": "high",
    },
    {
        "name": "Min Cell Voltage",
        "register": 37008,
        "scale": 0.001,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "min_cell_voltage",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 3,
        "scan_interval": "high",
    },
    {
        "name": "Battery Cycle Count",
        "register": 34003,
        "scale": 1,
        "icon": "mdi:counter",
        "state_class": "total_increasing",
        "category": "diagnostic",
        "key": "battery_cycle_count",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "scan_interval": "low",
    },
    {
        "name": "Device Name",
        "register": 31000,
        "count": 10,
        "data_type": "char",
        "unit": None,
        "icon": "mdi:package-variant-closed",
        "key": "device_name",
        "enabled_by_default": True,
        "scan_interval": "very_low",
        "precision": 0,
    },
    {
        "name": "BMS Version",
        "register": 30204,
        "unit": None,
        "icon": "mdi:battery-check-outline",
        "category": "diagnostic",
        "key": "bms_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "name": "VMS Version",
        "register": 30202,
        "unit": None,
        "icon": "mdi:battery-check-outline",
        "category": "diagnostic",
        "key": "vms_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "name": "EMS Version",
        "register": 30200,
        "unit": None,
        "icon": "mdi:ticket-confirmation-outline",
        "category": "diagnostic",
        "key": "ems_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "scale": 1,
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "name": "Comm Module Firmware",
        "register": 30350,
        "count": 6,
        "unit": None,
        "icon": "mdi:ticket-confirmation-outline",
        "category": "diagnostic",
        "key": "comm_module_firmware",
        "enabled_by_default": True,
        "data_type": "char",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "name": "MAC Address",
        "register": 30304,
        "count": 6,
        "unit": None,
        "icon": "mdi:ethernet",
        "key": "mac_address",
        "enabled_by_default": True,
        "data_type": "char",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "name": "WiFi Signal Strength",
        "register": 30303,
        "scale": -1,
        "unit": "dBm",
        "device_class": "signal_strength",
        "state_class": "measurement",
        "key": "wifi_signal_strength",
        "enabled_by_default": True,
        "data_type": "uint16",
        "category": "diagnostic",
        "precision": 0,
        "scan_interval": "low",
    },
]

BINARY_SENSOR_DEFINITIONS_V3 = [
    {
        "name": "WiFi Status",
        "register": 30300,
        "data_type": "uint16",
        "unit": None,
        "category": "diagnostic",
        "device_class": "connectivity",
        "icon": "mdi:check-network-outline",
        "key": "wifi_status",
        "enabled_by_default": True,
        "scan_interval": "low",
    },
    {
        "name": "Cloud Status",
        "register": 30302,
        "data_type": "uint16",
        "unit": None,
        "category": "diagnostic",
        "device_class": "connectivity",
        "icon": "mdi:cloud-outline",
        "key": "cloud_status",
        "enabled_by_default": False,
        "scan_interval": "low",
    },
    {
        "name": "Balancing Mode",
        "register": 34009,
        "data_type": "uint16",
        "unit": None,
        "category": "diagnostic",
        "device_class": "running",
        "icon": "mdi:scale-balance",
        "key": "balancing_mode",
        "enabled_by_default": True,
        "scan_interval": "low",
    },
]

SELECT_DEFINITIONS_V3 = [
    {
        "register": 42010,
        "name": "Force Mode",
        "key": "force_mode",
        "enabled_by_default": False,
        "scan_interval": "high",
        "data_type": "uint16",
        "options": {"stop": 0, "charge": 1, "discharge": 2},
    },
    {
        "name": "User Work Mode",
        "register": 43000,
        "key": "user_work_mode",
        "enabled_by_default": False,
        "data_type": "uint16",
        "scan_interval": "high",
        "use_shadow_state": True,
        "options": {"manual": 0, "anti_feed": 1, "trade_mode": 2},
    },
]

SWITCH_DEFINITIONS_V3 = [
    {
        "register": 41200,
        "command_on": 0,
        "command_off": 1,
        "name": "Backup Function",
        "key": "backup_function",
        "enabled_by_default": True,
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        # RS485 communication control mode switch
        "name": "RS485 Control Mode",
        "register": 42000,
        "command_on": 21930,  # 0x55AA in decimal
        "command_off": 21947,  # 0x55BB in decimal
        "key": "rs485_control_mode",
        "enabled_by_default": True,
        "data_type": "uint16",
        "scan_interval": "medium",
    },
]

NUMBER_DEFINITIONS_V3 = [
    {
        "register": 42020,
        "name": "Set Charge Power",
        "key": "set_charge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-up-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 42021,
        "name": "Set Discharge Power",
        "key": "set_discharge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-down-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44002,
        "name": "Max Charge Power",
        "key": "max_charge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-up-outline",
        "min": 800,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44003,
        "name": "Max Discharge Power",
        "key": "max_discharge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-down-outline",
        "min": 800,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
]

BUTTON_DEFINITIONS_V3 = [
    {
        "register": 41000,
        "command": 21930,
        "icon": "mdi:restart",
        "category": "diagnostic",
        "name": "Reset Device",
        "key": "reset_device",
        "enabled_by_default": False,
        "data_type": "uint16",
    },
]

EFFICIENCY_SENSOR_DEFINITIONS_V3 = [
    {
        "key": "round_trip_efficiency_total",
        "name": "Round-Trip Efficiency Total",
        "unit": "%",
        "state_class": "measurement",
        "dependency_keys": {
            "charge": "total_charging_energy",
            "discharge": "total_discharging_energy",
        },
    },
]

STORED_ENERGY_SENSOR_DEFINITIONS_V3 = [
    {
        "name": "Stored Energy",
        "key": "stored_energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
        "dependency_keys": {
            "soc": "battery_soc",
            "capacity": "battery_total_energy"
        },
    }
]
